services:
  - type: web
    name: crypto-backend
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt && python manage.py migrate --no-input && python manage.py collectstatic --no-input
    startCommand: gunicorn config.wsgi:application --bind 0.0.0.0:$PORT

