services:
  - type: web
    name: crypto-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application --log-file -
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: localhost,127.0.0.1
